# -*- coding: utf-8 -*-
"""text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/167wvwfoc7YR10u3iJPp-bTRmW6ZKUwDD
"""

import streamlit as st
import tensorflow as tf
from tensorflow.keras.preprocessing.sequence import pad_sequences
import json
import re

# Load model and word index
model = tf.keras.models.load_model("sentiment_model.h5")
with open("word_index.json") as f:
    word_index = json.load(f)

max_len = 200

def encode_review(text):
    text = re.sub(r"[^a-zA-Z0-9\s]", "", text.lower())  # Clean text
    tokens = text.split()
    encoded = [word_index.get(word, 2) for word in tokens]  # Unknown word = 2
    return pad_sequences([encoded], maxlen=max_len, padding='post')

# Streamlit UI
st.title("🎬 IMDb Sentiment Classifier")
review = st.text_area("Enter your movie review below:", height=150)

if st.button("Predict"):
    if review.strip() == "":
        st.warning("Please enter a review.")
    else:
        prediction = model.predict(encode_review(review))[0][0]
        label = "🟢 Positive" if prediction > 0.5 else "🔴 Negative"
        st.markdown(f"**Prediction:** {label} ({prediction:.2f})")